### ISSUE TITLE
Add replaceInOrder for faster call the replacement of the same function

### ISSUE THREAD

**Issue by wppunk** [lucatume/function-mocker#11]
I have a case where I use one function several times in a row. For example, `filter_input`. It is not very convenient to use anonymous functions:

```
public function test_case() {
	$answers = [ 'one', 'two' ];
	FunctionMocker::replace(
		'filter_input',
		function () use ($answers) {
			static $i = 0;

			return $answers[ $i ++ ];
		}
	);

	$this->assertSame(
		'one',
		filter_input( INPUT_POST, 'first_use', FILTER_SANITIZE_STRING )
	);
	$this->assertSame(
		'two',
		filter_input( INPUT_POST, 'second_use', FILTER_SANITIZE_STRING )
	);
}
```

It would be nice to add method `replaceInOrder` for a shorter record:

```
public function test_case() {
	FunctionMocker::replaceInOrder( 'filter_input', [ 'one', 'two' ] );

	$this->assertSame(
		'one',
		filter_input( INPUT_POST, 'first_use', FILTER_SANITIZE_STRING )
	);
	$this->assertSame(
		'two',
		filter_input( INPUT_POST, 'second_use', FILTER_SANITIZE_STRING )
	);
}
```

**Comment by lucatume** [comment]
@wppunk (excellent name, by the way) this is an excellent idea.

In cases such as this I, usually, use generators to return different values, but I can see how adding this method would add value to the library API.

I will keep this updated with news.

**Comment by wppunk** [comment]
I can do PR for the master branch

**Comment by lucatume** [comment]
You're welcome to.

**Comment by wppunk** [comment]
@lucatume PR ready. Make a code review please.

**Comment by wppunk** [comment]
@lucatume Something with the build and `FunctionMocker::replaceInOrder` unavailable from the composer.

**Comment by lucatume** [comment]
> @lucatume Something with the build and `FunctionMocker::replaceInOrder` unavailable from the composer.

@wppunk There have been no changes since the merge of this branch, if it did work before, it should keep working, could you be more specific? Would you mind opening a new issue on the repository to track it there?
