### ISSUE TITLE
Support PHP8.0

### ISSUE THREAD

**Issue by wppunk** [lucatume/function-mocker#14]
Need to support for PHP8.0

**Comment by lucatume** [comment]
This would be an enhancement, for sure.

PHP 8 is not yet supported on Travis CI, I've created a [PR to test this out, though](https://github.com/lucatume/function-mocker/pull/15)

**Comment by lucatume** [comment]
Fixed by #17

**Comment by lucatume** [comment]
And many thanks to @kagg-design  for the work.
