### ISSUE TITLE
Infinite loop when FunctionMocker can't find the vendor directory

### ISSUE THREAD

**Issue by andreasciamanna** [lucatume/function-mocker#2]
I've stumbled in a project where the vendor directory does not exist (actually, it does exist but with a different name).

`\tad\FunctionMocker\Utils::findParentContainingFrom` tries to find the first directory called "vendor" from the current directory and up.

This logic has two consequences:

1. "vendor" is hard-coded: perhaps `\tad\FunctionMocker\FunctionMocker::setUp` could accept an optional argument to specify the name of the vendor directory?
2. Once `\tad\FunctionMocker\Utils::findParentContainingFrom` reaches the root directory, it continues forever checking that same root directory.  
    I think a simple fix could be to check that `$dir !== ''/'` right before calling `$dir = dirname($dir);` and, in this case, gracefully fail.

Not a blocking issue for me. The original developers of the project I'm working with, are most likely going to start using the "vendor" directory, as most of the rest of the world :)

I just wanted to report it.

**Comment by lucatume** [comment]
Thanks for reporting it.

I admit the "hard-coding" has always left me kinda "meh"; I think I can do better than that. Adding this to my to-do list.
