### ISSUE TITLE
Patchwork 2.0 works with internal functions but function-mocker does not.

### ISSUE THREAD

**Issue by krodyrobi** [lucatume/function-mocker#3]
Patchwork can redefine for instance `time()` calls if a proper entry in patchworks.json is added before patchwork's init. I have the file but for some reason the mocker explicitly checks to see if it is a system function an bails out. Is there a more deeper reason why this is not supported? or it's an artifact of a previous version.

https://github.com/lucatume/function-mocker/blob/master/src/tad/FunctionMocker/Checker.php#L18

**Comment by lucatume** [comment]
Thanks for bringing this up.

As you correctly guessed the missing system function mocking feature is an artifact of the previous version. 
I'll get to correct this when back to work next week and update the ticket.

**Comment by krodyrobi** [comment]
Something is off if I remove the checks and add a patchworks.json and run just the new test the callverifier does not count properly,  but if I run the whole test suite it never finishes, nothing gets executed after the spy checks.

[changes](https://github.com/krodyrobi/function-mocker/compare/master...krodyrobi:internal_functions)

I'll have another look on monday, but this seems deeper than I thought.

**Comment by lucatume** [comment]
Thanks for looking into this. 
I'll have a look too the coming week and report back here.
