### ISSUE TITLE
Composer installs dependencies even with phpunit 6, deprecated imports

### ISSUE THREAD

**Issue by krodyrobi** [lucatume/function-mocker#4]
First of all thank you for #3 !

Given the following block:
```
  "require-dev": {
    "phpunit/phpunit": "^6.1",
    "lucatume/function-mocker": "^1.0"
  }
```

It successfully installs `function-mocker: 1.2` and `phpunit 6.1` on `php 7.1.4` .
But from the config in this repo it shouldn't allow a phpunit version >= 6.0 .

The reason I'm reporting this is because
some imports like `PHPUnit_Framework_Assert` will not work in phpunit 6+ (reproducible when calling `wasCalledWithOnce` on a redefinition).

Is there any chance that phpunit >=6.0 will be supported?
Maybe on a separate branch, even if features won't be added as often?

**Comment by lucatume** [comment]
Thanks for reporting the issue, I've made `phpunit/phpunit: ~5.4` a requirement in version `1.2.2` of the library and, with the configuration you reported, version `1.2.0` is installed thus the breakage.
Lowering the configuration version of phpunit to ~5.0 in the `composer.json` file makes it:

```json
"require-dev": {
    "phpunit/phpunit": "~5.0",
    "lucatume/function-mocker": "1.2.2"
}
```

That's still an hack though and not an ideal solution.  
Yes: I want function mocker to support PHPUnit 6 and am working on it and plan to keep a single branch. Keeping this issue up to update.
