### ISSUE TITLE
Redefine "filter_input" or "time"

### ISSUE THREAD

**Issue by ridaamirini** [lucatume/function-mocker#5]
I tried to redefine the Method but nothing happens.

 `FunctionMocker::replace('filter_input','TEST');`

`$this->assertEquals('Test', filter_input(INPUT_POST, 'name', FILTER_SANITIZE_STRING));`

Patchwork.json 

`
{
  "redefinable-internals": [
    "filter_input",
    "time"
  ]
}
`

**Comment by lucatume** [comment]
I guess this is a documentation issue.
If you look at the repository test files you will see here: https://github.com/lucatume/function-mocker/blob/master/tests/_bootstrap.php
That the way to setup Function Mocker (and the underlying Patchwork framework) is to use the `FunctionMocker::init` method.
I'm updating the documentation as there is no mention to it.

**Comment by lucatume** [comment]
How about this? https://github.com/lucatume/function-mocker#bootstrapping
Does it make things clearer?

**Comment by ridaamirini** [comment]
Thank u its better. I will try it now.

**Comment by ridaamirini** [comment]
Thank u works!
